// Generated by Supabase. Do not edit by hand.
// Regenerate with the Supabase MCP `generate_typescript_types` (project: nascente)
// or `supabase gen types typescript` against project ref djnhodhdpjxkiqehixsf.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  public: {
    Tables: {
      reading_plan_days: {
        Row: {
          book_id: number | null;
          chapter_end: number | null;
          chapter_start: number | null;
          created_at: string;
          day: number;
          id: string;
          plan_id: string;
          ref_label: string;
          sort_order: number;
        };
        Insert: {
          book_id?: number | null;
          chapter_end?: number | null;
          chapter_start?: number | null;
          created_at?: string;
          day: number;
          id?: string;
          plan_id: string;
          ref_label: string;
          sort_order?: number;
        };
        Update: {
          book_id?: number | null;
          chapter_end?: number | null;
          chapter_start?: number | null;
          created_at?: string;
          day?: number;
          id?: string;
          plan_id?: string;
          ref_label?: string;
          sort_order?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'reading_plan_days_plan_id_fkey';
            columns: ['plan_id'];
            isOneToOne: false;
            referencedRelation: 'reading_plans';
            referencedColumns: ['id'];
          },
        ];
      };
      reading_plans: {
        Row: {
          cadence: Database['public']['Enums']['plan_cadence'];
          created_at: string;
          description: string | null;
          id: string;
          is_ai_generated: boolean;
          lang: string;
          owner_id: string | null;
          slug: string | null;
          title: string;
          total_days: number;
          updated_at: string;
        };
        Insert: {
          cadence?: Database['public']['Enums']['plan_cadence'];
          created_at?: string;
          description?: string | null;
          id?: string;
          is_ai_generated?: boolean;
          lang?: string;
          owner_id?: string | null;
          slug?: string | null;
          title: string;
          total_days: number;
          updated_at?: string;
        };
        Update: {
          cadence?: Database['public']['Enums']['plan_cadence'];
          created_at?: string;
          description?: string | null;
          id?: string;
          is_ai_generated?: boolean;
          lang?: string;
          owner_id?: string | null;
          slug?: string | null;
          title?: string;
          total_days?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_reading_plan_completions: {
        Row: {
          completed_at: string;
          day: number;
          id: string;
          user_id: string;
          user_plan_id: string;
        };
        Insert: {
          completed_at?: string;
          day: number;
          id?: string;
          user_id: string;
          user_plan_id: string;
        };
        Update: {
          completed_at?: string;
          day?: number;
          id?: string;
          user_id?: string;
          user_plan_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_reading_plan_completions_user_plan_id_fkey';
            columns: ['user_plan_id'];
            isOneToOne: false;
            referencedRelation: 'user_reading_plans';
            referencedColumns: ['id'];
          },
        ];
      };
      user_reading_plans: {
        Row: {
          completed_at: string | null;
          created_at: string;
          current_day: number;
          id: string;
          plan_id: string;
          started_at: string;
          status: Database['public']['Enums']['user_plan_status'];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          completed_at?: string | null;
          created_at?: string;
          current_day?: number;
          id?: string;
          plan_id: string;
          started_at?: string;
          status?: Database['public']['Enums']['user_plan_status'];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          completed_at?: string | null;
          created_at?: string;
          current_day?: number;
          id?: string;
          plan_id?: string;
          started_at?: string;
          status?: Database['public']['Enums']['user_plan_status'];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_reading_plans_plan_id_fkey';
            columns: ['plan_id'];
            isOneToOne: false;
            referencedRelation: 'reading_plans';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      plan_cadence: 'daily';
      user_plan_status: 'active' | 'completed' | 'archived';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      plan_cadence: ['daily'],
      user_plan_status: ['active', 'completed', 'archived'],
    },
  },
} as const;
