#!/usr/bin/env node
/**
 * Syncs the version fields in app.json after a package.json version bump.
 *
 * `android/` and `ios/` are gitignored and regenerated by `expo prebuild` (CNG),
 * so the native version fields must NEVER be hand-edited — prebuild overwrites
 * `build.gradle` and `project.pbxproj` on every run. `app.json` is the single
 * source of truth; prebuild propagates it:
 *
 *   expo.version            → Android versionName + iOS MARKETING_VERSION
 *   expo.android.versionCode → Android versionCode
 *   expo.ios.buildNumber     → iOS CURRENT_PROJECT_VERSION
 *
 * The marketing version (`expo.version`) is what users see and may repeat
 * across builds; the build numbers must STRICTLY INCREASE per store upload, or
 * Play/App Store Connect reject the artifact. They are therefore bumped on
 * every run, independently of which semver component changed — a resubmission
 * of the same marketing version still needs a fresh build number.
 *
 * Both stores are kept on the same integer deliberately: it makes a build
 * number unambiguous across platforms when tracing a crash report or a store
 * listing back to a commit. iOS takes it as a string (Apple's
 * CFBundleVersion is a string type); Android takes it as a number.
 *
 * Usage:
 *   node scripts/sync-version.mjs <marketing-version>   # e.g. 1.2.0
 */

import { readFileSync, writeFileSync } from 'node:fs';

const APP_JSON = 'app.json';

const version = process.argv[2];
if (!version) {
  console.error('Usage: node scripts/sync-version.mjs <marketing-version>');
  process.exit(1);
}

// Guard against a malformed tag reaching the native config, where a bad value
// surfaces much later as an opaque Gradle/Xcode failure.
if (!/^\d+\.\d+\.\d+$/.test(version)) {
  console.error(`Invalid marketing version: "${version}" (expected e.g. 1.2.0)`);
  process.exit(1);
}

const app = JSON.parse(readFileSync(APP_JSON, 'utf8'));

// Default to 0 so a first run lands on 1 — matching the versionCode prebuild
// generates when the field is absent, so the first CI bump is not a regression.
const previous = Number(app.expo.android?.versionCode ?? 0);
if (!Number.isInteger(previous) || previous < 0) {
  console.error(`Invalid existing versionCode: ${app.expo.android?.versionCode}`);
  process.exit(1);
}
const build = previous + 1;

app.expo.version = version;
app.expo.android = { ...app.expo.android, versionCode: build };
app.expo.ios = { ...app.expo.ios, buildNumber: String(build) };

writeFileSync(APP_JSON, `${JSON.stringify(app, null, 2)}\n`);

console.log(`version=${version} build=${build}`);

// Surfaced as step outputs so later workflow steps (and the commit message) can
// reference the build number without re-parsing app.json.
if (process.env.GITHUB_OUTPUT) {
  const { appendFileSync } = await import('node:fs');
  appendFileSync(process.env.GITHUB_OUTPUT, `build=${build}\n`);
}
